/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"
import { registry } from '../registry/index';

// biome-ignore lint/suspicious/noExplicitAny: Auto-generated registry index with dynamic component types
export const Index: Record<string, any> = {
  "typography": {
    name: "typography",
    description: "A set of typographic components for consistent text styling.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/helisa/ui/typography.tsx",
      type: "registry:ui",
      target: "components/helisa/ui/typography.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/helisa/ui/typography.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "required-mark": {
    name: "required-mark",
    description: "A simple asterisk to indicate required fields.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/helisa/ui/required-mark.tsx",
      type: "registry:ui",
      target: "components/helisa/ui/required-mark.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/helisa/ui/required-mark.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "layout-container": {
    name: "layout-container",
    description: "A flexible container component for layout purposes.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/helisa/ui/layout-container.tsx",
      type: "registry:ui",
      target: "components/helisa/ui/layout-container.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/helisa/ui/layout-container.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "custom-skeleton": {
    name: "custom-skeleton",
    description: "A customizable skeleton loader component.",
    type: "registry:ui",
    registryDependencies: ["skeleton"],
    files: [{
      path: "registry/helisa/ui/custom-skeleton.tsx",
      type: "registry:ui",
      target: "components/helisa/ui/custom-skeleton.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/helisa/ui/custom-skeleton.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "select-multi": {
    name: "select-multi",
    description: "A multi-select with badges",
    type: "registry:ui",
    registryDependencies: ["badge","button","command","popover","separator"],
    files: [{
      path: "registry/helisa/ui/select-multi.tsx",
      type: "registry:ui",
      target: "components/helisa/ui/select-multi.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/helisa/ui/select-multi.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "form-field": {
    name: "form-field",
    description: "A component for form field layout and validation.",
    type: "registry:ui",
    registryDependencies: ["label","input","textarea","select","switch","checkbox","field","https://raw.githubusercontent.com/helisaapp/helisa-react-registry/refs/heads/main/public/r/required-mark.json"],
    files: [{
      path: "registry/helisa/ui/form-field.tsx",
      type: "registry:ui",
      target: "components/helisa/ui/form-field.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/helisa/ui/form-field.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "date-utils": {
    name: "date-utils",
    description: "A set of utility functions for date manipulation and formatting.",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "registry/helisa/lib/date-utils.ts",
      type: "registry:lib",
      target: "lib/date-utils.ts"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/helisa/lib/date-utils.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "use-print": {
    name: "use-print",
    description: "A hook that handles printing functionality.",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/helisa/hooks/usePrint.tsx",
      type: "registry:hook",
      target: "hooks/usePrint.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/helisa/hooks/usePrint.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "use-debounce": {
    name: "use-debounce",
    description: "A hook that debounces a value over a specified delay.",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/helisa/hooks/useDebounce.tsx",
      type: "registry:hook",
      target: "hooks/useDebounce.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/helisa/hooks/useDebounce.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }